package runner;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;

import com.jcabi.github.Github;
import com.jcabi.github.Repo;
import com.jcabi.github.Repos;
import com.jcabi.github.Repos.RepoCreate;
import com.jcabi.github.RtGithub;

import command.ExecuteCommand;
import data_structures.Que;
import parser.CSVParser;
import parser.IllegalDataException;
import parser.IllegalHeaderException;

import com.jcabi.github.Coordinates;

public class Main {
	private static String currentDir = System.getProperty("user.dir");
	private static String pathToFile = currentDir + "\\src\\main\\resources\\Book1.csv";
	
	
	
	public static void main(String[] args) throws IOException {
		/*
		File file = new File(pathToFile);
		Scanner sc = new Scanner(file);
		String topLine = sc.nextLine();
		CSVParser csvp = new CSVParser();
		csvp.parseCSVHeader(topLine);
		Que<ExecuteCommand> commandQue = new Que<ExecuteCommand>();
		int x = 1;
		while (sc.hasNextLine()) {
			String nextLine = sc.nextLine();
			ExecuteCommand cmd = csvp.parseLine(nextLine);
			System.out.println("line [" + x + "] under the header: name is: " + cmd.getRepoName());
			commandQue.enque(cmd);
			x++;
		}
		
		sc.close();
		*/
		
		/*
		Runtime rt = Runtime.getRuntime();
		rt.exec("cmd/c cd C:\\Users\\Administrator\\Desktop");
		rt.exec("mkdir javatest");
		rt.exec("cd javatest");
		rt.exec("git clone https://github.com/ShalomGottesman/CompOrg.git");
		*/
		ProcessBuilder processBuilder = new ProcessBuilder();
		processBuilder.command("cmd.exe", "/C", "start" 
				,"cd", "C:\\Users\\Administrator\\Desktop" 
				//,"timeout", "2"
				//,"mkdir", "javatest"
				//,"timeout", "2"
				//,"cd javatest"//
				//,"git clone https://github.com/ShalomGottesman/CompOrg.git"
				);
		try {

			Process process = processBuilder.start();

			StringBuilder output = new StringBuilder();

			BufferedReader reader = new BufferedReader(
					new InputStreamReader(process.getInputStream()));

			String line;
			while ((line = reader.readLine()) != null) {
				output.append(line + "\n");
			}

			int exitVal = process.waitFor();
			if (exitVal == 0) {
				System.out.println("Success!");
				System.out.println(output);
				System.exit(0);
			} else {
				//abnormal...
			}

		} catch (IOException e) {
			e.printStackTrace();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}	}
	/*
	public static void main(String[] args) throws IOException {
		Github github = new RtGithub("ShalomGottesman", "");
		Repos reps = github.repos();
		RepoCreate repc = new Repos.RepoCreate("testingRepo3", false)
				.withDescription("This repository was generated by TeachHub, an abstraction of the GitHub api, written by Shalom Gottesman")
				.withAutoInit(true)
				;
		
		reps.create(repc);
		Coordinates cord = new Coordinates.Simple("ShalomGottesman","testingRepo3");
		Repo repo = reps.get(cord);
		repo.collaborators().add("sgottes1");
	}
	*/

}
