package runner;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

import com.jcabi.github.Github;
import com.jcabi.github.Repo;
import com.jcabi.github.Repos;
import com.jcabi.github.Repos.RepoCreate;
import com.jcabi.github.RtGithub;

import command.ExecuteCommand;
import data_structures.Que;
import parser.CSVParser;

import com.jcabi.github.Coordinates;

public class Main {
	private static String currentDir = System.getProperty("user.dir");
	private static String pathToFile = currentDir + "\\src\\main\\resources\\Book1.csv";
	
	
	public static void main(String[] args) throws FileNotFoundException {
		File file = new File(pathToFile);
		Scanner sc = new Scanner(file);
		String topLine = sc.nextLine();
		CSVParser csvp = new CSVParser();
		csvp.parseCSVHeader(topLine);
		Que<ExecuteCommand> commandQue = new Que<ExecuteCommand>();
		int x = 1;
		while (sc.hasNextLine()) {
			String nextLine = sc.nextLine();
			ExecuteCommand cmd = csvp.parseLine(nextLine);
			System.out.println("line [" + x + "] under the header: name is: " + cmd.getRepoName());
			commandQue.enque(cmd);
			x++;
		}
		
		sc.close();
		
	}
	/*
	public static void main(String[] args) throws IOException {
		Github github = new RtGithub("ShalomGottesman", "");
		Repos reps = github.repos();
		RepoCreate repc = new Repos.RepoCreate("testingRepo3", false)
				.withDescription("This repository was generated by TeachHub, an abstraction of the GitHub api, written by Shalom Gottesman")
				.withAutoInit(true)
				;
		
		reps.create(repc);
		Coordinates cord = new Coordinates.Simple("ShalomGottesman","testingRepo3");
		Repo repo = reps.get(cord);
		repo.collaborators().add("sgottes1");
	}
	*/

}
